kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
  extraPortMappings:
  - containerPort: 8082
    hostPort: 8082
    protocol: TCP