apiVersion: v1
kind: ConfigMap
metadata:
  name: default-proxy-preprocessor-rules-config
  namespace: observability-system
data:
  rules.yaml: |
    'global':
      - rule: metrics-add-cluster-uuid
        action: addTagIfNotExists
        tag: cluster_uuid
        value: "{{ .DataExport.WavefrontProxy.ClusterUUID }}"
      - rule: metrics-add-cluster-name
        action: addTagIfNotExists
        tag: cluster
        value: "{{ .ClusterName }}"
      - rule: span-add-cluster-uuid
        action: spanAddTagIfNotExists
        tag: cluster_uuid
        value: "{{ .DataExport.WavefrontProxy.ClusterUUID }}"
      - rule: span-add-cluster-name
        action: spanAddTagIfNotExists
        tag: cluster
        value: "{{ .ClusterName }}"