apiVersion: v1
kind: ServiceAccount
metadata:
  name: wavefront-proxy
  labels:
    app.kubernetes.io/name: wavefront
    app.kubernetes.io/component: proxy
  namespace: {{ .Namespace }}
  ownerReferences:
  - apiVersion: apps/v1
    kind: Deployment
    name: wavefront-controller-manager
    uid: {{ .ControllerManagerUID }}
automountServiceAccountToken: false