{{- if .Openshift }}
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: wavefront-proxy-scc
  namespace: system
  labels:
    app.kubernetes.io/name: wavefront
    app.kubernetes.io/component: proxy
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegedContainer: false
readOnlyRootFilesystem: true
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: MustRunAs
users:
- system:serviceaccount:observability-system:wavefront-proxy
{{- end }}