# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - directory: "/collector"
    package-ecosystem: "gomod"
    schedule:
      interval: "daily"
      time: "13:00" # 6am MST
    # reasoning: use exclude rules for things we will not upgrade in a timely manner
    ignore:
      - dependency-name: "k8s.io/*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: "sigs.k8s.io/*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
    groups:
      k8s.io:
        patterns: ["k8s.io/*"]
        update-types: ["patch"]

  - directory: "/operator"
    package-ecosystem: "gomod"
    schedule:
      interval: "daily"
      time: "14:00" # 7am MST
    # reasoning: use exclude rules for things we will not upgrade in a timely manner
    ignore:
      - dependency-name: "k8s.io/*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: "sigs.k8s.io/*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
    groups:
      k8s.io:
        patterns: ["k8s.io/*"]
        update-types: ["patch"]

  - directory: "/operator/pixie-sizer"
    package-ecosystem: "gomod"
    schedule:
      interval: "daily"
      time: "14:30" # 7:30am MST
    # reasoning: use exclude rules for things we will not upgrade in a timely manner
    ignore:
      - dependency-name: "k8s.io/*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: "sigs.k8s.io/*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
    groups:
      k8s.io:
        patterns: ["k8s.io/*"]
        update-types: ["patch"]

  - directory: "/test-proxy"
    package-ecosystem: "gomod"
    schedule:
      interval: "daily"
      time: "15:00" # 8am MST
    # reasoning: use exclude rules for things we will not upgrade in a timely manner
    ignore:
      - dependency-name: "k8s.io/*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: "sigs.k8s.io/*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
    groups:
      k8s.io:
        patterns: ["k8s.io/*"]
        update-types: ["patch"]

  - directory: "/.github/docker-dependabot"
    package-ecosystem: "docker"
    schedule:
      interval: "daily"
