# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/collector" # Location of package manifests
    schedule:
      interval: "daily"
      time: "13:00" # 6am MST
    # reasoning: use exclude rules for things we will not upgrade in a timely manner
    ignore:
      - dependency-name: "k8s.io/*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: "sigs.k8s.io/*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/operator" # Location of package manifests
    schedule:
      interval: "daily"
      time: "14:00" # 7am MST
    # reasoning: use exclude rules for things we will not upgrade in a timely manner
    ignore:
      - dependency-name: "k8s.io/*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: "sigs.k8s.io/*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/operator/pixie-sizer" # Location of package manifests
    schedule:
      interval: "daily"
      time: "14:30" # 7:30am MST
    # reasoning: use exclude rules for things we will not upgrade in a timely manner
    ignore:
      - dependency-name: "k8s.io/*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: "sigs.k8s.io/*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/test-proxy" # Location of package manifests
    schedule:
      interval: "daily"
      time: "15:00" # 8am MST
    # reasoning: use exclude rules for things we will not upgrade in a timely manner
    ignore:
      - dependency-name: "k8s.io/*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: "sigs.k8s.io/*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
  - package-ecosystem: "docker"
    directory: "/.github/docker-dependabot"
    schedule:
      interval: "daily"
