resource_types:
  - name: gitlab
    type: registry-image
    source:
      repository: devtools-docker.artifactory.eng.vmware.com/vmware/runway/resourcetypes/gitlab-resource
      tag: 1.0.0

resources:
  - name: observability-for-kubernetes
    type: git
    source:
      uri: git@github.com:wavefrontHQ/observability-for-kubernetes.git
      private_key: ((osspi.jcornish-github-private-key)) # TODO use a deploy key

jobs:
  - name: update-self
    plan:
    - get: observability-for-kubernetes
      trigger: true
    - set_pipeline: observability-for-kubernetes-osspi
      file: observability-for-kubernetes/osspi/pipeline.yaml
  - name: osspi-scan-collector
    serial: true
    plan:
      - in_parallel:
          - get: observability-for-kubernetes
            trigger: true
            params: { submodules: all }
      - in_parallel:
        - task: osspi-scan-packages
          file: observability-for-kubernetes/osspi/tasks/osspi/run-osspi-source.yaml
          input_mapping:
            ci_repo: observability-for-kubernetes
            project_repo: observability-for-kubernetes
          params:
            SCAN_PATH: collector
            REPO: project_repo
            API_KEY: ((osspi.osm-prod-api-key))
            USERNAME: ((osspi.osm-prod-username))
            PRODUCT: WavefrontKubernetesCollector
            VERSION: Latest
            PREPARE: |
              go mod vendor
            OSSPI_SCANNING_PARAMS: |
              enable: true
              include_bomtools: "go_mod"
              search_depth: 5
              go_mod.path: "/go/bin/go"

              # exclude for signature scans
              exclude_patterns:
                - vendor
            OSSPI_IGNORE_RULES: |
              - name_regex: onsi\/ginkgo
                version_regex: .*
              - name_regex: gomega
                version_regex: .*

  - name: osspi-scan-operator
    serial: true
    plan:
      - in_parallel:
        - get: observability-for-kubernetes
          trigger: true
          params: { submodules: all }
      - in_parallel:
        - task: osspi-scan-packages
          file: observability-for-kubernetes/osspi/tasks/osspi/run-osspi-source.yaml
          input_mapping:
            ci_repo: observability-for-kubernetes
            project_repo: observability-for-kubernetes
          params:
            SCAN_PATH: operator
            REPO: project_repo
            API_KEY: ((osspi.osm-prod-api-key))
            USERNAME: ((osspi.osm-prod-username))
            PRODUCT: Wavefront_K8_Operator
            VERSION: Latest
            PREPARE: |
              go mod vendor
            OSSPI_SCANNING_PARAMS: |
              enable: true
              include_bomtools: "go_mod"
              search_depth: 5
              go_mod.path: "/go/bin/go"

              # exclude for signature scans
              exclude_patterns:
                - vendor
            OSSPI_IGNORE_RULES: |
              - name_regex: onsi\/ginkgo
                version_regex: .*
              - name_regex: gomega
                version_regex: .*
        - task: osspi-scan-docker
          file: observability-for-kubernetes/osspi/tasks/osspi/run-osspi-docker.yaml
          input_mapping:
            ci_repo: observability-for-kubernetes
          params:
            IMAGE: projects.registry.vmware.com/tanzu_observability/kubernetes-operator-fluentd
            TAG: 1.0.3-1.15.2
            API_KEY: ((osspi.osm-prod-api-key))
            USERNAME: ((osspi.osm-prod-username))
            PRODUCT: Wavefront_K8_Operator
            VERSION: Latest
            APPEND: true

