resource_types:
  - name: gitlab
    type: registry-image
    source:
      repository: devtools-docker.artifactory.eng.vmware.com/vmware/runway/resourcetypes/gitlab-resource
      tag: 1.0.0
resources:
  - name: observability-for-kubernetes
    type: git
    source:
      uri: git@github.com:wavefrontHQ/observability-for-kubernetes.git
      private_key: ((osspi.jcornish-github-private-key)) # TODO use a deploy key
  - name: wavefront-kubernetes-adapter
    type: git
    source:
      uri: git@github.com:wavefrontHQ/wavefront-kubernetes-adapter.git
      private_key: ((osspi.jcornish-github-private-key)) # TODO use a deploy key
  - name: prometheus-storage-adapter
    type: git
    source:
      uri: git@github.com:wavefrontHQ/prometheus-storage-adapter.git
      private_key: ((osspi.jcornish-github-private-key)) # TODO use a deploy key
  - name: wavefront-sdk-java
    type: git
    source:
      uri: https://github.com/wavefrontHQ/wavefront-sdk-java.git
  - name: wavefront-spring-boot
    type: git
    source:
      uri: https://github.com/wavefrontHQ/wavefront-spring-boot.git
      branch: springboot3
  - name: osspi-tool
    type: git
    icon: gitlab
    source:
      uri: git@gitlab.eng.vmware.com:source-insight-tooling/norsk-to-osspi.git
      private_key: ((osspi.jcornish-github-private-key)) # TODO use a deploy key
      branch: main
jobs:
  - name: update-self
    plan:
    - get: observability-for-kubernetes
      trigger: true
    - set_pipeline: observability-for-kubernetes-osspi
      file: observability-for-kubernetes/osspi/pipeline.yaml
  - name: osspi-scan-collector
    serial: true
    plan:
      - in_parallel:
          - get: observability-for-kubernetes
            trigger: true
            params: { submodules: all }
      - in_parallel:
        - task: osspi-scan-packages
          file: observability-for-kubernetes/osspi/tasks/osspi/run-osspi-source.yaml
          input_mapping:
            ci_repo: observability-for-kubernetes
            project_repo: observability-for-kubernetes
          params:
            SCAN_PATH: collector
            REPO: project_repo
            API_KEY: ((osspi.osm-prod-api-key))
            USERNAME: ((osspi.osm-prod-username))
            PRODUCT: WavefrontKubernetesCollector
            VERSION: Latest
            PREPARE: |
              go mod vendor
            OSSPI_SCANNING_PARAMS: |
              enable: true
              include_bomtools: "go_mod"
              search_depth: 5
              go_mod.path: "/go/bin/go"

              # exclude for signature scans
              exclude_patterns:
                - vendor
            OSSPI_IGNORE_RULES: |
              - name_regex: onsi\/ginkgo
                version_regex: .*
              - name_regex: gomega
                version_regex: .*
  - name: osspi-scan-operator
    serial: true
    plan:
      - in_parallel:
        - get: observability-for-kubernetes
          trigger: true
          params: { submodules: all }
      - in_parallel:
        - task: osspi-scan-packages
          attempts: 3
          file: observability-for-kubernetes/osspi/tasks/osspi/run-osspi-source.yaml
          input_mapping:
            ci_repo: observability-for-kubernetes
            project_repo: observability-for-kubernetes
          params:
            SCAN_PATH: operator
            REPO: project_repo
            API_KEY: ((osspi.osm-prod-api-key))
            USERNAME: ((osspi.osm-prod-username))
            PRODUCT: Wavefront_K8_Operator
            VERSION: Latest
            PREPARE: |
              go mod vendor
            OSSPI_SCANNING_PARAMS: |
              enable: true
              include_bomtools: "go_mod"
              search_depth: 5
              go_mod.path: "/go/bin/go"

              # exclude for signature scans
              exclude_patterns:
                - vendor
            OSSPI_IGNORE_RULES: |
              - name_regex: onsi\/ginkgo
                version_regex: .*
              - name_regex: gomega
                version_regex: .*
        - task: osspi-scan-fluentbit
          file: observability-for-kubernetes/osspi/tasks/osspi/run-osspi-docker.yaml
          input_mapping:
            ci_repo: observability-for-kubernetes
          params:
            IMAGE: projects.registry.vmware.com/tanzu_observability/kubernetes-operator-fluentbit
            TAG: 2.1.6
            API_KEY: ((osspi.osm-prod-api-key))
            USERNAME: ((osspi.osm-prod-username))
            PRODUCT: Wavefront_K8_Operator
            VERSION: Latest
            APPEND: true
  - name: osspi-scan-wavefront-kubernetes-adapter
    serial: true
    plan:
    - in_parallel:
      - get: observability-for-kubernetes
        params: { submodules: all }
      - get: wavefront-kubernetes-adapter
        trigger: true
        params: { submodules: all }
    - in_parallel:
      - task: osspi-scan-packages
        file: observability-for-kubernetes/osspi/tasks/osspi/run-osspi-source.yaml
        input_mapping:
          ci_repo: observability-for-kubernetes
          project_repo: wavefront-kubernetes-adapter
        params:
          REPO: project_repo
          API_KEY: ((osspi.osm-prod-api-key))
          USERNAME: ((osspi.osm-prod-username))
          PRODUCT: WavefrontKubernetesAdapter
          VERSION: Latest
          PREPARE: |
            go mod vendor
          OSSPI_SCANNING_PARAMS: |
            enable: true
            include_bomtools: "go_mod"
            search_depth: 5
            go_mod.path: "/go/bin/go"
            # exclude for signature scans
            exclude_patterns:
              - vendor
          OSSPI_IGNORE_RULES: |
            - name_regex: onsi\/ginkgo
              version_regex: .*
            - name_regex: gomega
              version_regex: .*
  - name: osspi-scan-prometheus-storage-adapter
    serial: true
    plan:
    - in_parallel:
      - get: observability-for-kubernetes
        params: { submodules: all }
      - get: prometheus-storage-adapter
        trigger: true
        params: { submodules: all }
    - in_parallel:
      - task: osspi-scan-packages
        file: observability-for-kubernetes/osspi/tasks/osspi/run-osspi-source.yaml
        input_mapping:
          ci_repo: observability-for-kubernetes
          project_repo: prometheus-storage-adapter
        params:
          REPO: project_repo
          API_KEY: ((osspi.osm-prod-api-key))
          USERNAME: ((osspi.osm-prod-username))
          PRODUCT: PrometheusStorageAdapter
          VERSION: Latest
          PREPARE: |
            go mod vendor
          OSSPI_SCANNING_PARAMS: |
            enable: true
            include_bomtools: "go_mod"
            search_depth: 5
            go_mod.path: "/go/bin/go"
            # exclude for signature scans
            exclude_patterns:
              - vendor
          OSSPI_IGNORE_RULES: |
            - name_regex: onsi\/ginkgo
              version_regex: .*
            - name_regex: gomega
              version_regex: .*

  - name: osspi-scan-wavefront-sdk-java
    serial: true
    plan:
    - in_parallel:
      - get: osspi-tool
      - get: wavefront-sdk-java
        trigger: true
        params: { submodules: all }
    - in_parallel:
      - task: osspi-scan-packages
        file: osspi-tool/tasks/osspi/run-osspi-source.yaml
        input_mapping:
          repo1: osspi-tool
          repo2: wavefront-sdk-java
        params:
          REPO: repo2
          API_KEY: ((osspi.osm-prod-api-key))
          USERNAME: ((osspi.osm-prod-username))
          OSM_ENVIRONMENT: production
          PRODUCT: wavefront-sdk-java
          VERSION: Latest
          PREPARE: |
            curl --output /tmp/maven.tar.gz https://dlcdn.apache.org/maven/maven-3/3.9.4/binaries/apache-maven-3.9.4-bin.tar.gz
            tar -xf /tmp/maven.tar.gz -C /tmp
          OSSPI_SCANNING_PARAMS: |
            enable: true
            include_bomtools: "maven"
            maven.path: /tmp/apache-maven-3.9.4/bin/mvn
            maven.exclude_scopes: "test"
            search_depth: 5
            # exclude for signature scans
            exclude_patterns:
            - test

  - name: osspi-scan-wavefront-spring-boot
    serial: true
    plan:
    - in_parallel:
      - get: osspi-tool
      - get: wavefront-spring-boot
        trigger: true
        params: { submodules: all }
    - in_parallel:
      - task: osspi-scan-packages
        file: osspi-tool/tasks/osspi/run-osspi-source.yaml
        input_mapping:
          repo1: osspi-tool
          repo2: wavefront-spring-boot
        params:
          REPO: repo2
          API_KEY: ((osspi.osm-prod-api-key))
          USERNAME: ((osspi.osm-prod-username))
          OSM_ENVIRONMENT: production
          PRODUCT: WavefrontSprintBootAutoconfigure
          VERSION: Latest
          PREPARE: |
            curl --output /tmp/maven.tar.gz https://dlcdn.apache.org/maven/maven-3/3.9.4/binaries/apache-maven-3.9.4-bin.tar.gz
            tar -xf /tmp/maven.tar.gz -C /tmp
          OSSPI_SCANNING_PARAMS: |
            enable: true
            include_bomtools: "maven"
            maven.path: /tmp/apache-maven-3.9.4/bin/mvn
            maven.exclude_scopes: "test"
            search_depth: 5
            # exclude for signature scans
            exclude_patterns:
            - test
