resource_types:
  - name: gitlab
    type: registry-image
    source:
      repository: devtools-docker.artifactory.eng.vmware.com/vmware/runway/resourcetypes/gitlab-resource
      tag: 1.0.0
resources:
  - name: observability-for-kubernetes
    type: git
    source:
      uri: git@github.com:wavefrontHQ/observability-for-kubernetes.git
      private_key: ((osspi.jcornish-github-private-key)) # TODO use a deploy key
      branch: K8SSAAS-1845-pixie-osl
  - name: wavefront-kubernetes-adapter
    type: git
    source:
      uri: git@github.com:wavefrontHQ/wavefront-kubernetes-adapter.git
      private_key: ((osspi.jcornish-github-private-key)) # TODO use a deploy key
  - name: prometheus-storage-adapter
    type: git
    source:
      uri: git@github.com:wavefrontHQ/prometheus-storage-adapter.git
      private_key: ((osspi.jcornish-github-private-key)) # TODO use a deploy key
jobs:
  - name: update-self
    plan:
    - get: observability-for-kubernetes
      trigger: true
    - set_pipeline: observability-for-kubernetes-osspi
      file: observability-for-kubernetes/osspi/pipeline.yaml
  - name: osspi-scan-collector
    serial: true
    plan:
      - in_parallel:
          - get: observability-for-kubernetes
            trigger: true
            params: { submodules: all }
      - in_parallel:
        - task: osspi-scan-packages
          file: observability-for-kubernetes/osspi/tasks/osspi/run-osspi-source.yaml
          input_mapping:
            ci_repo: observability-for-kubernetes
            project_repo: observability-for-kubernetes
          params:
            SCAN_PATH: collector
            REPO: project_repo
            API_KEY: ((osspi.osm-prod-api-key))
            USERNAME: ((osspi.osm-prod-username))
            PRODUCT: WavefrontKubernetesCollector
            VERSION: Latest
            PREPARE: |
              go mod vendor
            OSSPI_SCANNING_PARAMS: |
              enable: true
              include_bomtools: "go_mod"
              search_depth: 5
              go_mod.path: "/go/bin/go"

              # exclude for signature scans
              exclude_patterns:
                - vendor
            OSSPI_IGNORE_RULES: |
              - name_regex: onsi\/ginkgo
                version_regex: .*
              - name_regex: gomega
                version_regex: .*
  - name: osspi-scan-operator
    serial: true
    plan:
      - in_parallel:
        - get: observability-for-kubernetes
          trigger: true
          params: { submodules: all }
      - in_parallel:
          limit: 3
          steps:
          - task: osspi-scan-packages
            attempts: 3
            file: observability-for-kubernetes/osspi/tasks/osspi/run-osspi-source.yaml
            input_mapping:
              ci_repo: observability-for-kubernetes
              project_repo: observability-for-kubernetes
            params:
              SCAN_PATH: operator
              REPO: project_repo
              API_KEY: ((osspi.osm-prod-api-key))
              USERNAME: ((osspi.osm-prod-username))
              PRODUCT: Wavefront_K8_Operator
              VERSION: Latest
              PREPARE: |
                go mod vendor
              OSSPI_SCANNING_PARAMS: |
                enable: true
                include_bomtools: "go_mod"
                search_depth: 5
                go_mod.path: "/go/bin/go"
  
                # exclude for signature scans
                exclude_patterns:
                  - vendor
              OSSPI_IGNORE_RULES: |
                - name_regex: onsi\/ginkgo
                  version_regex: .*
                - name_regex: gomega
                  version_regex: .*
          - task: osspi-scan-docker
            file: observability-for-kubernetes/osspi/tasks/osspi/run-osspi-docker.yaml
            input_mapping:
              ci_repo: observability-for-kubernetes
            params:
              IMAGE: projects.registry.vmware.com/tanzu_observability/kubernetes-operator-fluentbit
              TAG: 2.1.2
              API_KEY: ((osspi.osm-prod-api-key))
              USERNAME: ((osspi.osm-prod-username))
              PRODUCT: Wavefront_K8_Operator
              VERSION: Latest
              APPEND: true
          - task: osspi-scan-pixie-kelvin
            file: observability-for-kubernetes/osspi/tasks/osspi/run-osspi-binary.yaml
            input_mapping:
              ci_repo: observability-for-kubernetes
            params:
              IMAGE: projects.registry.vmware.com/tanzu_observability/kubernetes-operator-pixie-kelvin_image
              TAG: 0.13.2
              API_KEY: ((osspi.osm-prod-api-key))
              USERNAME: ((osspi.osm-prod-username))
              PRODUCT: Wavefront_K8_Operator
              VERSION: Latest
              APPEND: false
          - task: osspi-scan-pixie-query-broker
            file: observability-for-kubernetes/osspi/tasks/osspi/run-osspi-binary.yaml
            input_mapping:
              ci_repo: observability-for-kubernetes
            params:
              IMAGE: projects.registry.vmware.com/tanzu_observability/kubernetes-operator-pixie-query_broker_server_image
              TAG: 0.13.2
              API_KEY: ((osspi.osm-prod-api-key))
              USERNAME: ((osspi.osm-prod-username))
              PRODUCT: Wavefront_K8_Operator
              VERSION: Latest
              APPEND: false
          - task: osspi-scan-pixie-metadata
            file: observability-for-kubernetes/osspi/tasks/osspi/run-osspi-binary.yaml
            input_mapping:
              ci_repo: observability-for-kubernetes
            params:
              IMAGE: projects.registry.vmware.com/tanzu_observability/kubernetes-operator-pixie-metadata_server_image
              TAG: 0.13.2
              API_KEY: ((osspi.osm-prod-api-key))
              USERNAME: ((osspi.osm-prod-username))
              PRODUCT: Wavefront_K8_Operator
              VERSION: Latest
              APPEND: false
          - task: osspi-scan-pixie-pem
            file: observability-for-kubernetes/osspi/tasks/osspi/run-osspi-binary.yaml
            input_mapping:
              ci_repo: observability-for-kubernetes
            params:
              IMAGE: projects.registry.vmware.com/tanzu_observability/kubernetes-operator-pixie-pem_image
              TAG: 0.13.2
              API_KEY: ((osspi.osm-prod-api-key))
              USERNAME: ((osspi.osm-prod-username))
              PRODUCT: Wavefront_K8_Operator
              VERSION: Latest
              APPEND: false
          - task: osspi-scan-pixie-cert-provisioner
            file: observability-for-kubernetes/osspi/tasks/osspi/run-osspi-binary.yaml
            input_mapping:
              ci_repo: observability-for-kubernetes
            params:
              IMAGE: projects.registry.vmware.com/tanzu_observability/kubernetes-operator-pixie-cert_provisioner_image
              TAG: 0.13.2
              API_KEY: ((osspi.osm-prod-api-key))
              USERNAME: ((osspi.osm-prod-username))
              PRODUCT: Wavefront_K8_Operator
              VERSION: Latest
              APPEND: false
          - task: osspi-scan-pixie-curl
            file: observability-for-kubernetes/osspi/tasks/osspi/run-osspi-binary.yaml
            input_mapping:
              ci_repo: observability-for-kubernetes
            params:
              IMAGE: projects.registry.vmware.com/tanzu_observability/kubernetes-operator-pixie-curl:multiarch-7.87.0
              TAG: sha256:f7f265d5c64eb4463a43a99b6bf773f9e61a50aaa7cefaf564f43e42549a01dd
              API_KEY: ((osspi.osm-prod-api-key))
              USERNAME: ((osspi.osm-prod-username))
              PRODUCT: Wavefront_K8_Operator
              VERSION: Latest
              APPEND: false
              CT_TRACKER_OS: alpine
          - task: osspi-scan-pixie-nats
            file: observability-for-kubernetes/osspi/tasks/osspi/run-osspi-binary.yaml
            input_mapping:
              ci_repo: observability-for-kubernetes
            params:
              IMAGE: projects.registry.vmware.com/tanzu_observability/kubernetes-operator-pixie-nats:multiarch-2.8.4-alpine3.15
              TAG: sha256:988010f74b61749cfb82c28b50b47d26d0b972860ce6e9325a5afcde97713da2
              API_KEY: ((osspi.osm-prod-api-key))
              USERNAME: ((osspi.osm-prod-username))
              PRODUCT: Wavefront_K8_Operator
              VERSION: Latest
              APPEND: false
              CT_TRACKER_OS: alpine
  - name: osspi-scan-wavefront-kubernetes-adapter
    serial: true
    plan:
    - in_parallel:
      - get: observability-for-kubernetes
        params: { submodules: all }
      - get: wavefront-kubernetes-adapter
        trigger: true
        params: { submodules: all }
    - in_parallel:
      - task: osspi-scan-packages
        file: observability-for-kubernetes/osspi/tasks/osspi/run-osspi-source.yaml
        input_mapping:
          ci_repo: observability-for-kubernetes
          project_repo: wavefront-kubernetes-adapter
        params:
          REPO: project_repo
          API_KEY: ((osspi.osm-prod-api-key))
          USERNAME: ((osspi.osm-prod-username))
          PRODUCT: WavefrontKubernetesAdapter
          VERSION: Latest
          PREPARE: |
            go mod vendor
          OSSPI_SCANNING_PARAMS: |
            enable: true
            include_bomtools: "go_mod"
            search_depth: 5
            go_mod.path: "/go/bin/go"
            # exclude for signature scans
            exclude_patterns:
              - vendor
          OSSPI_IGNORE_RULES: |
            - name_regex: onsi\/ginkgo
              version_regex: .*
            - name_regex: gomega
              version_regex: .*
  - name: osspi-scan-prometheus-storage-adapter
    serial: true
    plan:
    - in_parallel:
      - get: observability-for-kubernetes
        params: { submodules: all }
      - get: prometheus-storage-adapter
        trigger: true
        params: { submodules: all }
    - in_parallel:
      - task: osspi-scan-packages
        file: observability-for-kubernetes/osspi/tasks/osspi/run-osspi-source.yaml
        input_mapping:
          ci_repo: observability-for-kubernetes
          project_repo: prometheus-storage-adapter
        params:
          REPO: project_repo
          API_KEY: ((osspi.osm-prod-api-key))
          USERNAME: ((osspi.osm-prod-username))
          PRODUCT: PrometheusStorageAdapter
          VERSION: Latest
          PREPARE: |
            go mod vendor
          OSSPI_SCANNING_PARAMS: |
            enable: true
            include_bomtools: "go_mod"
            search_depth: 5
            go_mod.path: "/go/bin/go"
            # exclude for signature scans
            exclude_patterns:
              - vendor
          OSSPI_IGNORE_RULES: |
            - name_regex: onsi\/ginkgo
              version_regex: .*
            - name_regex: gomega
              version_regex: .*