# Need to change YOUR_CLUSTER_NAME and YOUR_WAVEFRONT_URL accordingly
apiVersion: wavefront.com/v1alpha1
kind: Wavefront
metadata:
  name: wavefront
  namespace: observability-system
spec:
  clusterName: k8ssaas-1341-test
  wavefrontUrl: https://nimba.wavefront.com
  dataCollection:
    metrics:
      enable: true
  dataExport:
    wavefrontProxy:
      enable: true
      histogram:
        port: 40000
        minutePort: 40001
        hourPort: 40002
        dayPort: 40003
