apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-control-plane-config
  namespace: {{ .Namespace }}
  ownerReferences:
  - apiVersion: apps/v1
    kind: Deployment
    name: wavefront-controller-manager
    uid: {{ .ControllerManagerUID }}
  annotations:
    wavefront.com/discovery-config: 'true'
  labels:
    app.kubernetes.io/name: wavefront
    app.kubernetes.io/coØmponent: collector
data:
  collector.yaml: |
    plugins:
    - name: etcd-discovery
      type: prometheus
      selectors:
        images:
        - '*coredns:*'
        labels:
          k8s-app:
          - kube-dns
      port: 9153
      path: /metrics
      scheme: http
      prefix: kubernetes.controlplane.
      convertHistograms: true
      filters:
        metricAllowList:
        - 'kubernetes.controlplane.coredns.dns.request.duration.seconds.bucket'
        - 'kubernetes.controlplane.coredns.dns.responses.total.counter'