apiVersion: v1
kind: ConfigMap
metadata:
  name: apiserver-control-plane-config
  namespace: {{ .Namespace }}
  labels:
    app.kubernetes.io/name: wavefront
    app.kubernetes.io/component: collector
  annotations:
    wavefront.com/discovery-config: 'true'
    wavefront.com/conditionally-provision: '{{ .DataCollection.Metrics.ControlPlane.Enable }}'
  ownerReferences:
  - apiVersion: apps/v1
    kind: Deployment
    name: wavefront-controller-manager
    uid: {{ .ControllerManagerUID }}
data:
  collector.yaml: |
    plugins:
    - name: apiserver-discovery
      type: prometheus
      selectors:
        resourceType: service
        labels:
          components:
          - apiserver
          provider:
          - kubernetes
      port: 443
      path: /metrics
      scheme: https
      prefix: kubernetes.controlplane.
      convertHistograms: true
      filters:
        metricAllowList:
        - 'kubernetes.controlplane.apiserver.request.total.counter'
        - 'kubernetes.controlplane.apiserver.request.duration.seconds'
        - 'kubernetes.controlplane.apiserver.storage.objects.gauge'
      conf: |
        bearer_token_file: '/var/run/secrets/kubernetes.io/serviceaccount/token'
        tls_config:
          ca_file: '/var/run/secrets/kubernetes.io/serviceaccount/ca.crt'
          insecure_skip_verify_true: true
