{{- if and .DataCollection.Metrics.ControlPlane.Enable .Openshift }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: wavefront
    app.kubernetes.io/component: collector
  name: openshift-coredns-control-plane-config
  namespace: {{ .Namespace }}
  ownerReferences:
  - apiVersion: apps/v1
    kind: Deployment
    name: wavefront-controller-manager
    uid: {{ .ControllerManagerUID }}
  annotations:
    wavefront.com/discovery-config: 'true'
data:
  collector.yaml: |
    plugins:
    - name: openshift-coredns-discovery
      type: prometheus
      selectors:
        labels:
          dns.operator.openshift.io/daemonset-dns:
          - default
      port: 9154
      path: /metrics
      scheme: https
      prefix: kubernetes.controlplane.
      convertHistograms: true
      conf: |
        bearer_token_file: '/var/run/secrets/kubernetes.io/serviceaccount/token'
        tls_config:
          ca_file: '/etc/openshift-service-ca-bundle/service-ca.crt'
          server_name: 'dns-default.openshift-dns.svc'
{{- end }}
