apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-events-only-wavefront-collector-config
  namespace: {{ .Namespace }}
  annotations:
    wavefront.com/conditionally-provision: '{{ and (not .MetricsEnable) .KubernetesEvents.Enable }}'
data:
  config.yaml: |
    clusterName: {{ .ClusterName }}
    enableDiscovery: false
    defaultCollectionInterval: 10s
    flushInterval: 10s
    sinkExportDataTimeout: 20s

    sinks:
    - type: "external"
      enableEvents: true
      externalEndpointURL: "{{ .KubernetesEvents.IngestionUrl }}"
    events:
      filters:
        tagAllowList:
          important:
          - "true"
        tagDenyList:
          kind:
          - "Job"
    sources:
      kubernetes_source: {}