apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
  namespace: collector-targets
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: projects.registry.vmware.com/tanzu_observability_keights_saas/busybox:latest
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
