apiVersion: v1
kind: Pod
metadata:
  name: high-memory-usage-pod
spec:
  containers:
  - name: memory-hog
    image: busybox
    command: ["sh", "-c", "dd if=/dev/zero of=/dev/shm/memory-hog bs=1M count=46; tail -f /dev/null"]
    resources:
      limits:
        memory: "50Mi"
      requests:
        memory: "50Mi"
  - name: normal-container
    image: nginx
    resources:
      limits:
        memory: "200Mi"
      requests:
        memory: "100Mi"

