apiVersion: batch/v1
kind: Job
metadata:
  name: job-failure
  namespace: collector-targets
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 1
  template:
    metadata:
      name: job-failure
      labels:
        name: jobs
        exclude-me: "true"
    spec:
      restartPolicy: Never
      containers:
        - name: job-failure
          image: projects.registry.vmware.com/tanzu_observability_keights_saas/busybox:latest
          imagePullPolicy: IfNotPresent
          args:
            - /bin/sh
            - -c
            - date; echo I am down; exit 1
          resources:
            requests:
              cpu: 50m
              memory: 20Mi
            limits:
              cpu: 200m
              memory: 200Mi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: job-success
  namespace: collector-targets
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 2
  template:
    metadata:
      name: job-success
      labels:
        name: jobs
        exclude-me: "true"
    spec:
      restartPolicy: OnFailure
      containers:
        - name: job-success
          image: projects.registry.vmware.com/tanzu_observability_keights_saas/busybox:latest
          imagePullPolicy: IfNotPresent
          command: ["echo", "Running a job"]
          resources:
            requests:
              cpu: 50m
              memory: 20Mi
            limits:
              cpu: 200m
              memory: 200Mi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: job-failure-fixed-completion-count
  namespace: collector-targets
spec:
  completions: 12
  parallelism: 2
  backoffLimit: 1
  template:
    metadata:
      name: job-failure-fixed-completion-count
      labels:
        name: fixed-completion-count-jobs
        exclude-me: "true"
    spec:
      restartPolicy: Never
      containers:
      - name: job-failure-fixed-completion-count
        image: projects.registry.vmware.com/tanzu_observability_keights_saas/busybox:latest
        imagePullPolicy: IfNotPresent
        args:
        - /bin/sh
        - -c
        - date; echo I am down; exit 1
        resources:
          requests:
            cpu: 50m
            memory: 20Mi
          limits:
            cpu: 200m
            memory: 200Mi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: job-success-fixed-completion-count
  namespace: collector-targets
spec:
  completions: 2
  parallelism: 2
  backoffLimit: 12
  template:
    metadata:
      name: job-success-fixed-completion-count
      labels:
        name: fixed-completion-count-jobs
        exclude-me: "true"
    spec:
      restartPolicy: OnFailure
      containers:
      - name: job-success-fixed-completion-count
        image: projects.registry.vmware.com/tanzu_observability_keights_saas/busybox:latest
        imagePullPolicy: IfNotPresent
        args:
        - /bin/sh
        - -c
        - date; echo Running a job; exit 0
        resources:
          requests:
            cpu: 50m
            memory: 20Mi
          limits:
            cpu: 200m
            memory: 200Mi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: job-failure-work-queue
  namespace: collector-targets
spec:
  parallelism: 2
  backoffLimit: 2
  template:
    metadata:
      name: job-failure-work-queue
      labels:
        name: work-queue-jobs
        exclude-me: "true"
    spec:
      restartPolicy: Never
      containers:
      - name: job-failure-work-queue
        image: projects.registry.vmware.com/tanzu_observability_keights_saas/busybox:latest
        imagePullPolicy: IfNotPresent
        args:
        - /bin/sh
        - -c
        - date; echo I am down; exit 1
        resources:
          requests:
            cpu: 50m
            memory: 20Mi
          limits:
            cpu: 200m
            memory: 200Mi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: job-success-work-queue
  namespace: collector-targets
spec:
  parallelism: 2
  backoffLimit: 12
  template:
    metadata:
      name: job-success-work-queue
      labels:
        name: work-queue-jobs
        exclude-me: "true"
    spec:
      restartPolicy: OnFailure
      containers:
      - name: job-success-work-queue
        image: projects.registry.vmware.com/tanzu_observability_keights_saas/busybox:latest
        imagePullPolicy: IfNotPresent
        args:
        - /bin/sh
        - -c
        - date; echo Running a job; exit 0
        resources:
          requests:
            cpu: 50m
            memory: 20Mi
          limits:
            cpu: 200m
            memory: 200Mi
