apiVersion: v1
kind: Pod
metadata:
  labels:
    name: pod-completed
    exclude-me: "true"
  name: pod-completed
  namespace: collector-targets
spec:
  containers:
  - name: pod-completed
    image: projects.registry.vmware.com/tanzu_observability_keights_saas/busybox:latest
    imagePullPolicy: IfNotPresent
    args:
    - /bin/sh
    - -c
    - 'exit 0'
  restartPolicy: OnFailure
