apiVersion: v1
kind: Pod
metadata:
  labels:
    name: pod-cannot-be-scheduled
    exclude-me: "true"
  name: pod-cannot-be-scheduled
  namespace: collector-targets
spec:
  containers:
  - name: pod-cannot-be-scheduled
    image: projects.registry.vmware.com/tanzu_observability_keights_saas/busybox:latest
    resources:
      requests:
        cpu: 100m
        memory: 50G