apiVersion: v1
kind: Pod
metadata:
  labels:
    name: pod-crash-loop-backoff
    exclude-me: "true"
  name: pod-crash-loop-backoff
  namespace: collector-targets
spec:
  containers:
  - name: pod-crash-loop-backoff
    image: projects.registry.vmware.com/tanzu_observability_keights_saas/busybox:latest
    resources:
      requests:
        memory: 100Mi
      limits:
        memory: 200Mi
    args: [ /bin/sh, -c,
            'exit 1' ]
