apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: wavefront
    app.kubernetes.io/component: controller-manager
  name: controller-manager
  namespace: observability-system
automountServiceAccountToken: false
