apiVersion: v1
kind: Secret
metadata:
  annotations:
    
  creationTimestamp: null
  labels:
    
  name: pl-cluster-secrets
  namespace: observability-system
stringData:
  sentry-dsn: "<no value>"
  cluster-id: "hacked-out-cloud-connector"
