apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    
  labels:
    
    app: pl-monitoring
    component: vizier
    vizier-bootstrap: "true"
  name: pl-cert-provisioner-service-account
  namespace: observability-system
