- op: replace
  path: "/spec/template/spec/containers/0/imagePullPolicy"
  value: IfNotPresent
- op: replace
  path: "/spec/template/spec/containers/0/env/1"
  value:
    name: COLLECTOR_TAG
    value: "1.14.0"
