# Need to change YOUR_CLUSTER and YOUR_API_TOKEN accordingly
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: ""
  labels:
    app.kubernetes.io/component: controller-manager
    app.kubernetes.io/name: wavefront
  name: wavefront-proxy
  namespace: observability-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wavefront-proxy
  template:
    metadata:
      labels:
        app: wavefront-proxy
    spec:
      tolerations:
      - effect: NoSchedule
        key: kubernetes.io/arch
        value: arm64
      containers:
      - name: wavefront-proxy
        image: wavefronthq/proxy:13.7
        imagePullPolicy: IfNotPresent
        env:
          - name: WAVEFRONT_URL
            value: https://YOUR_CLUSTER.wavefront.com/api/
          - name: WAVEFRONT_TOKEN
            value: YOUR_API_TOKEN
        # Uncomment the below lines to consume Zipkin/Istio traces
        #- name: WAVEFRONT_PROXY_ARGS
        #  value: --traceZipkinListenerPorts 9411
        ports:
          - containerPort: 2878
            protocol: TCP
        # Uncomment the below lines to consume Zipkin/Istio traces
        #- containerPort: 9411
        #  protocol: TCP
        securityContext:
          privileged: false
---
apiVersion: v1
kind: Service
metadata:
  name: wavefront-proxy
  labels:
    app: wavefront-proxy
  namespace: observability-system
spec:
  ports:
  - name: wavefront
    port: 2878
    protocol: TCP
  # Uncomment the below lines to consume Zipkin/Istio traces
  #- name: http
  #  port: 9411
  #  targetPort: 9411
  #  protocol: TCP
  selector:
    app: wavefront-proxy
