apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: pl-monitoring
    component: vizier
    vizier-bootstrap: "true"
  name: pl-cert-provisioner-service-account
  namespace: {{ .Namespace }}
