apiVersion: v1
kind: Service
metadata:
  labels:
    app: pl-monitoring
    component: vizier
  name: kelvin-service
  namespace: {{ .Namespace }}
spec:
  clusterIP: None
  ports:
  - name: tcp-http2
    port: 59300
    protocol: TCP
    targetPort: 59300
  selector:
    app: pl-monitoring
    component: vizier
    name: kelvin
  type: ClusterIP
