apiVersion: v1
kind: Service
metadata:
  labels:
    app: pl-monitoring
    component: vizier
  name: vizier-metadata-svc
  namespace: {{ .Namespace }}
spec:
  ports:
  - name: tcp-http2
    port: 50400
    protocol: TCP
    targetPort: 50400
  selector:
    app: pl-monitoring
    component: vizier
    name: vizier-metadata
  type: ClusterIP
