apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: pl-monitoring
    component: vizier
  name: metadata-pv-claim
  namespace: {{ .Namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi
