apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pl-monitoring
    component: vizier
  name: vizier-query-broker
  namespace: {{ .Namespace }}
  annotations:
    wavefront.com/conditionally-provision: '{{ .TLSCertsSecretExists }}'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pl-monitoring
      component: vizier
      name: vizier-query-broker
  template:
    metadata:
      annotations:
        px.dev/metrics_port: "50300"
        px.dev/metrics_scrape: "true"
      labels:
        app: pl-monitoring
        component: vizier
        name: vizier-query-broker
        plane: control
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/os
                    operator: Exists
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
              - matchExpressions:
                  - key: beta.kubernetes.io/os
                    operator: Exists
                  - key: beta.kubernetes.io/os
                    operator: In
                    values:
                      - linux
      containers:
        - env:
            - name: PL_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: PL_CLUSTER_ID
              valueFrom:
                secretKeyRef:
                  key: cluster-id
                  name: pl-cluster-secrets
            - name: PL_SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  key: sentry-dsn
                  name: pl-cluster-secrets
                  optional: true
            - name: PL_JWT_SIGNING_KEY
              valueFrom:
                secretKeyRef:
                  key: jwt-signing-key
                  name: pl-cluster-secrets
            - name: PL_POD_IP_ADDRESS
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: PL_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: PL_CLOUD_ADDR
              valueFrom:
                configMapKeyRef:
                  key: PL_CLOUD_ADDR
                  name: pl-cloud-config
            - name: PL_DATA_ACCESS
              value: Full
            - name: PL_CRON_SCRIPT_SOURCES
              value: configmaps
          envFrom:
            - configMapRef:
                name: pl-tls-config
          image: projects.registry.vmware.com/tanzu_observability/pixie-oss/pixie-prod/vizier-query_broker_server_image:0.14.7
          livenessProbe:
            httpGet:
              path: /healthz
              port: 50300
              scheme: HTTPS
          name: app
          ports:
            - containerPort: 50300
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - mountPath: /certs
              name: certs
      initContainers:
        - command:
            - sh
            - -c
            - 'set -x; URL="https://${SERVICE_NAME}:${SERVICE_PORT}/healthz"; until [ $(curl -m 0.5 -s -o /dev/null -w "%{http_code}" -k ${URL}) -eq 200 ]; do echo "waiting for ${URL}"; sleep 2; done; '
          env:
            - name: SERVICE_NAME
              value: vizier-metadata-svc
            - name: SERVICE_PORT
              value: "50400"
          image: projects.registry.vmware.com/tanzu_observability/bitnami/os-shell:11
          name: mds-wait
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
      securityContext:
        fsGroup: 10100
        runAsGroup: 10100
        runAsNonRoot: true
        runAsUser: 10100
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: query-broker-service-account
      tolerations:
        - effect: NoSchedule
          key: kubernetes.io/arch
          operator: Equal
          value: amd64
        - effect: NoExecute
          key: kubernetes.io/arch
          operator: Equal
          value: amd64
        - effect: NoSchedule
          key: kubernetes.io/arch
          operator: Equal
          value: arm64
        - effect: NoExecute
          key: kubernetes.io/arch
          operator: Equal
          value: arm64
      volumes:
        - name: certs
          secret:
            secretName: service-tls-certs
        - configMap:
            name: proxy-envoy-config
          name: envoy-yaml
