apiVersion: v1
data:
  # Change this to your domain, if you have set up a domain and DNS rules for your cloud.
  PL_CLOUD_ADDR: "vzconn-service.plc.svc.cluster.local:51600"
  # Fill out a name for your cluster, otherwise it will be randomly generated.
  PL_CLUSTER_NAME: {{ .ClusterName }}
  # Change this to your domain, if you have set up a domain and DNS rules for your cloud.
  PL_UPDATE_CLOUD_ADDR: "api-service.plc.svc.cluster.local:51200"
kind: ConfigMap
metadata:
  name: pl-cloud-config
  namespace: {{ .Namespace }}
