apiVersion: v1
data:
  PL_CUSTOM_ANNOTATIONS: ""
  PL_CUSTOM_LABELS: ""
  PL_DISABLE_AUTO_UPDATE: "false"
  PL_ETCD_OPERATOR_ENABLED: "false"
  PL_MD_ETCD_SERVER: https://pl-etcd-client.pl.svc:2379
  PX_MEMORY_LIMIT: ""
  PX_MEMORY_REQUEST: ""
kind: ConfigMap
metadata:
  name: pl-cluster-config
  namespace: {{ .Namespace }}
