apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vss-k8s-collector
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    app.kubernetes.io/component: vss-k8s-collector
    app.kubernetes.io/name: wavefront
rules:
- apiGroups:
  - rbac.authorization.k8s.io
  - networking.k8s.io
  - extensions
  - rbac
  - batch
  - apps
  - ""
  resources:
  - configmaps
  - endpoints
  - events
  - limitranges
  - persistentvolumes
  - persistentvolumeclaims
  - namespaces
  - podtemplates
  - resourcequotas
  - secrets
  - clusterrolebindings
  - services
  - serviceaccounts
  - networkpolicies
  - ingresses
  - ingressclasses
  - rolebindings
  - clusterroles
  - roles
  - cronjobs
  - jobs
  - replicationcontrollers
  - statefulsets
  - daemonsets
  - deployments
  - replicasets
  - pods
  - nodes
  verbs:
  - get
  - watch
  - list
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vss-k8s-collector
  labels:
    app.kubernetes.io/name: wavefront
    app.kubernetes.io/component: vss-k8s-collector
subjects:
- kind: ServiceAccount
  namespace: observability-system
  name: vss-k8s-collector
roleRef:
  kind: ClusterRole
  name: vss-k8s-collector
  apiGroup: rbac.authorization.k8s.io