# Source: telegraf-collector/templates/telegraf-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: telegraf
  namespace: {{ .Namespace }}
spec:
  ports:
  - name: otlp-grpc
    port: 4317
    protocol: TCP
    targetPort: 4317
  - name: prom
    port: 9273
    protocol: TCP
    targetPort: 9273
  selector:
    app.kubernetes.io/component: telegraf
    app.kubernetes.io/name: wavefront
