# Source: telegraf-collector/templates/telegraf-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
  namespace: {{ .Namespace }}
  labels:
    app.kubernetes.io/component: telegraf
    app.kubernetes.io/name: wavefront
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/component: telegraf
      app.kubernetes.io/name: wavefront
  template:
    metadata:
      labels:
        app.kubernetes.io/component: telegraf
        app.kubernetes.io/name: wavefront
    spec:
      containers:
      - name: telegraf
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
          requests:
            cpu: 200m
            memory: 400Mi

        image: "projects.registry.vmware.com/adie/telegraf:321-9fcaf1c-1120661547"
        imagePullPolicy: IfNotPresent
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Experimental.KubernetesEvents.SecretName }}
              key: k8s-events-endpoint-token
        - name: CLUSTER_CLOUD_ACCOUNT_ID
          value: {{ .Experimental.Hub.ClusterCloudAccountID }}
        - name: CLUSTER_CLOUD_PROVIDER
          value: {{ .Experimental.Hub.ClusterCloudProvider }}
        - name: CLUSTER_NAME
          value: {{ .ClusterName }}
        - name: CLUSTER_REGION
          value: {{ .Experimental.Hub.ClusterRegion }}
        - name: HTTP_INGESTION_URL
          value: {{ .Experimental.Hub.TSSMetricsUrl }}
        - name: METRICS_DOMAIN
          value: {{ .Experimental.Hub.TSSMetricsDomain }}
        - name: ORG_ID
          value: {{ .Experimental.Hub.CSPOrgID }}
        - name: TRACE_ENTITY_ID
          value: "{{ .Experimental.Hub.TelegrafTraceEntityID }}"
        - name: TRACE_METRIC
          value: "{{ .Experimental.Hub.TelegrafTraceMetric }}"
        ports:
        - containerPort: 4317
        - containerPort: 9273
        args:
        - --config
        - /config/telegraf.conf
        - --config-directory
        - /config-extra/
        volumeMounts:

        - name: config
          mountPath: /config/
          readOnly: true
        - name: config-extra
          mountPath: /config-extra/
          readOnly: true
        - name: config-plugins
          mountPath: /config-plugins/
          readOnly: true
      volumes:

      - name: data
        emptyDir:
          {}
      - name: config
        configMap:
          name: telegraf-configmap
          items:
          - key: telegraf.conf
            path: telegraf.conf
          - key: entityid-proc.star
            path: entityid-proc.star
      - name: config-extra
        configMap:
          name: telegraf-configmap
          items:
          - key: telegraf-extra.conf
            path: telegraf-extra.conf
      - name: config-plugins
        configMap:
          name: telegraf-configmap
          items:
          - key: telegraf-aws.conf
            path: telegraf-aws.conf
          - key: telegraf-azure.conf
            path: telegraf-azure.conf
          - key: telegraf-gcp.conf
            path: telegraf-gcp.conf
