apiVersion: v1
kind: Secret
metadata:
  annotations:
    
  creationTimestamp: null
  labels:
    
  name: pl-deploy-secrets
  namespace: observability-system
stringData:
  deploy-key: {{ .Experimental.AutoInstrumentation.DeployKey }}
