apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: pl-monitoring
    component: vizier
    vizier-bootstrap: "true"
    app.kubernetes.io/name: wavefront
    app.kubernetes.io/component: pixie
  name: pl-cert-provisioner-service-account
  namespace: observability-system
  ownerReferences:
    - apiVersion: apps/v1
      kind: Deployment
      name: wavefront-controller-manager
      uid: '{{ .ControllerManagerUID }}'
