apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    
  labels:
    
    app: pl-monitoring
    component: vizier
    vizier-bootstrap: "true"
  name: cloud-conn-service-account
  namespace: observability-system
