apiVersion: v1
kind: Service
metadata:
  annotations:
    
  labels:
    
    app: pl-monitoring
    etcd_cluster: pl-etcd
  name: pl-etcd
  namespace: observability-system
spec:
  clusterIP: None
  ports:
  - name: client
    port: 2379
  - name: peer
    port: 2380
  publishNotReadyAddresses: true
  selector:
    app: pl-monitoring
    etcd_cluster: pl-etcd
