apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: pl-monitoring
    component: vizier
    app.kubernetes.io/name: wavefront
    app.kubernetes.io/component: pixie
  name: metadata-pv-claim
  namespace: observability-system
  ownerReferences:
    - apiVersion: apps/v1
      kind: Deployment
      name: wavefront-controller-manager
      uid: '{{ .ControllerManagerUID }}'
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi
