apiVersion: v1
kind: Service
metadata:
  annotations:
    
  labels:
    
    app: pl-monitoring
    component: vizier
  name: kelvin-service
  namespace: observability-system
spec:
  clusterIP: None
  ports:
  - name: tcp-http2
    port: 59300
    protocol: TCP
    targetPort: 59300
  selector:
    app: pl-monitoring
    component: vizier
    name: kelvin
  type: ClusterIP
