apiVersion: v1
kind: Service
metadata:
  labels:
    app: pl-monitoring
    etcd_cluster: pl-etcd
  name: pl-etcd-client
  namespace: observability-system
spec:
  ports:
  - name: etcd-client
    port: 2379
  selector:
    app: pl-monitoring
    etcd_cluster: pl-etcd
