apiVersion: v1
kind: Service
metadata:
  labels:
    app: pl-monitoring
    name: pl-nats
    app.kubernetes.io/name: wavefront
    app.kubernetes.io/component: pixie
  name: pl-nats
  namespace: observability-system
  ownerReferences:
    - apiVersion: apps/v1
      kind: Deployment
      name: wavefront-controller-manager
      uid: '{{ .ControllerManagerUID }}'
spec:
  ports:
    - name: client
      port: 4222
  selector:
    app: pl-monitoring
    name: pl-nats
