apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    
  labels:
    
    app: pl-monitoring
    component: vizier
    vizier-bootstrap: "true"
  name: pl-updater-role
  namespace: observability-system
rules:
- apiGroups:
  - ""
  - apps
  - rbac.authorization.k8s.io
  - extensions
  - batch
  - policy
  resources:
  - configmaps
  - secrets
  - pods
  - services
  - deployments
  - daemonsets
  - persistentvolumes
  - roles
  - rolebindings
  - serviceaccounts
  - statefulsets
  - cronjobs
  - jobs
  verbs:
  - '*'
