apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    
  labels:
    
    app: pl-monitoring
    component: vizier
    vizier-bootstrap: "true"
  name: pl-updater-cluster-role
  namespace: observability-system
rules:
- apiGroups:
  - rbac.authorization.k8s.io
  - etcd.database.coreos.com
  - nats.io
  resources:
  - clusterroles
  - clusterrolebindings
  - persistentvolumes
  - etcdclusters
  - natsclusters
  verbs:
  - '*'
