apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: pl-monitoring
    component: vizier
  name: pl-vizier-metadata
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - namespaces
  verbs:
  - watch
  - get
  - list
- apiGroups:
  - apps
  resources:
  - replicasets
  - deployments
  verbs:
  - watch
  - get
  - list
