# Need to change YOUR_CLUSTER_NAME, YOUR_WAVEFRONT_URL and YOUR_IMAGE_REGISTRY_SECRET accordingly
apiVersion: wavefront.com/v1alpha1
kind: Wavefront
metadata:
  name: wavefront
  namespace: observability-system
spec:
  clusterName: YOUR_CLUSTER_NAME
  wavefrontUrl: YOUR_WAVEFRONT_URL
  # First follow steps for setting imagePullSecret for the operator at below link
  # https://github.com/wavefrontHQ/observability-for-kubernetes/blob/main/docs/operator/custom-configuration.md.
  # Set the image registry secret below for the operator components to authenticate with a private custom registry.
  imagePullSecret: YOUR_IMAGE_REGISTRY_SECRET
  dataCollection:
    metrics:
      enable: true
  dataExport:
    wavefrontProxy:
      enable: true