# Need to change YOUR_CLUSTER_NAME and YOUR_WAVEFRONT_URL accordingly
apiVersion: wavefront.com/v1alpha1
kind: Wavefront
metadata:
  name: wavefront
  namespace: observability-system
spec:
  clusterName: YOUR_CLUSTER_NAME
  wavefrontUrl: YOUR_WAVEFRONT_URL
  dataCollection:
    metrics:
      enable: true
  dataExport:
    wavefrontProxy:
      enable: true
      preprocessor: advanced-proxy-preprocessor-rules
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: advanced-proxy-preprocessor-rules
  namespace: observability-system
data:
  rules.yaml: |
    '2878':
      - rule: tag-all-metrics-processed
        action: addTag
        tag: processed
        value: "true"
      # only allow points listed under "names"
      - rule: allow-selected-metrics
        action: metricsFilter
        function: allow
        opts:
          cacheSize: 10000
        names:
        # allows a metric called metrics.1 but drops metrics.1.test
        - "metrics.1"
        # allows any metric that starts with metrics.2
        # Note: notice the use of "\\" as an escape character instead
        # of "\" (which is the defacto escape character used for regex)
        - "/metrics\\.2.*/"
        # allows any metric that ends with .ok
        - "/.*.ok$/"