# Need to change YOUR_CLUSTER_NAME and YOUR_WAVEFRONT_URL
# See https://github.com/wavefrontHQ/observability-for-kubernetes/blob/main/docs/experimental/autotracing.md for more details
apiVersion: wavefront.com/v1alpha1
kind: Wavefront
metadata:
  name: wavefront
  namespace: observability-system
spec:
  clusterName: YOUR_CLUSTER_NAME
  wavefrontUrl: YOUR_WAVEFRONT_URL
  dataCollection:
    metrics:
      enable: true
  dataExport:
    wavefrontProxy:
      enable: true
  experimental:
    autotracing:
      enable: true