apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  labels:
    app: pl-monitoring
    component: vizier
    app.kubernetes.io/name: wavefront
    app.kubernetes.io/component: pixie
  name: pl-vizier-query-broker-role
  namespace: observability-system
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
