apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    
  labels:
    
    app: pl-monitoring
    component: vizier
    vizier-bootstrap: "true"
  name: pl-cloud-connector-binding
  namespace: observability-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pl-cloud-connector-ns-role
subjects:
- kind: ServiceAccount
  name: cloud-conn-service-account
  namespace: observability-system
