apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    
  labels:
    
    app: pl-monitoring
    component: vizier
  name: pl-vizier-metadata-cluster-binding
  namespace: observability-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pl-vizier-metadata
subjects:
- kind: ServiceAccount
  name: metadata-service-account
  namespace: observability-system
