apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:

  labels:

    app: pl-monitoring
    component: vizier
    vizier-bootstrap: "true"
  name: pl-cloud-connector-binding
  namespace: observability-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pl-cloud-connector-ns-role
subjects:
- kind: ServiceAccount
  name: cloud-conn-service-account
  namespace: observability-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:

  labels:

    app: pl-monitoring
    component: vizier
    vizier-bootstrap: "true"
  name: pl-updater-binding
  namespace: observability-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pl-updater-role
subjects:
- kind: ServiceAccount
  name: pl-updater-service-account
  namespace: observability-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:

  labels:

    app: pl-monitoring
    component: vizier
  name: pl-vizier-crd-binding
  namespace: observability-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pl-vizier-crd-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: observability-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:

  labels:

    app: pl-monitoring
    component: vizier
  name: pl-vizier-crd-metadata-binding
  namespace: observability-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pl-vizier-crd-role
subjects:
- kind: ServiceAccount
  name: metadata-service-account
  namespace: observability-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:

  labels:

    app: pl-monitoring
    component: vizier
  name: pl-vizier-metadata-binding
  namespace: observability-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pl-vizier-metadata-role
subjects:
- kind: ServiceAccount
  name: metadata-service-account
  namespace: observability-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:

  labels:

    app: pl-monitoring
    component: vizier
    vizier-bootstrap: "true"
  name: pl-cloud-connector-cluster-binding
  namespace: observability-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pl-cloud-connector-role
subjects:
- kind: ServiceAccount
  name: cloud-conn-service-account
  namespace: observability-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:

  labels:

    app: pl-monitoring
    component: vizier
  name: pl-node-view-cluster-binding
  namespace: observability-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pl-node-view
subjects:
- kind: ServiceAccount
  name: default
  namespace: observability-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:

  labels:

    app: pl-monitoring
    component: vizier
    vizier-bootstrap: "true"
  name: pl-updater-cluster-binding
  namespace: observability-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pl-updater-role
subjects:
- kind: ServiceAccount
  name: pl-updater-service-account
  namespace: observability-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:

  labels:

    app: pl-monitoring
    component: vizier
  name: pl-vizier-metadata-cluster-binding
  namespace: observability-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pl-vizier-metadata
subjects:
- kind: ServiceAccount
  name: metadata-service-account
  namespace: observability-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:

  labels:

    app: pl-monitoring
    component: vizier
  name: pl-vizier-metadata-node-view-cluster-binding
  namespace: observability-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pl-node-view
subjects:
- kind: ServiceAccount
  name: metadata-service-account
  namespace: observability-system